site_name: BRV
site_author: drake
site_description: BRV框架文档
copyright: Copyright &copy; 2018 - 2020 劉強東

repo_name: GitHub
repo_url: https://github.com/liangjingkanji/BRV

extra_css:
  - css/extra.css

docs_dir: 'docs'

theme:
  name: material
  custom_dir: docs/material

  palette:
    scheme: drake
    primary: white

  font: false

  language: en

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed

nav:
  - Usage: index.md
  - Multi-type: multi-type.md
  - Data Refresh: refresh-data.md
  - Click Event: click.md
  - Lifecycle: lifecycle.md
  - Smooth Scrolling: performance.md
  - Header/Footer Layout: header_footer.md
  - Grouping: group.md
  - Hover: hover.md
  - Dividers:
      - Linear List: divider-linear.md
      - Grid List: divider-grid.md
      - Staggered Grid List: divider-staggerd.md
      - Custom: divider-other.md
  - Empty State: state.md
  - Pull-to-Refresh/Load-more: refresh.md
  - Refresh Animation: refresh-animate.md
  - Upfetch: upfetch.md
  - Preload: preload.md
  - Mode Switching: toggle.md
  - Selection Mode: checked.md
  - Flexbox Layout: flexbox.md
  - Drag and Drop: drag.md
  - Swipe: swipe.md
  - List Animation: animation.md
  - Data Interfaces: item.md
  - Recycle List: recycle.md
  - Extension Functions: extension.md
  - Network Requests: net.md
  - ViewBinding: view-binding.md
  - FAQ: issues.md
  - Third-Party Components: component.md
  - Changelog: updates.md
  - 1.x Documentation: api/index.html

